### ISSUE TITLE
Minor bug

### ISSUE THREAD

**Issue by Lutando** [DmitrySikorsky/AspNetCoreUploadingProgress#1]
Hi there thanks for the sample
There's a minor bug that causes the upload to fail silently (ive run into this problem before) because the "uploads" directory does not exist. To fix, you just add an uploads directory into `wwwroot`. Don't think this problem would happen on *nix.

Windows 10 x64

**Comment by DmitrySikorsky** [comment]
Wow, this is good you have found it, I will fix! Thanks!

**Comment by DmitrySikorsky** [comment]
Fixed!
