### ISSUE TITLE
Handle Progress for multiple sessions?

### ISSUE THREAD

**Issue by Neuroforge** [DmitrySikorsky/AspNetCoreUploadingProgress#2]
Great work on the solution.

What is the best way to handle the Progress update for multiple sessions?

Regards,

Daniel  
```

  // This is not the best idea to use a static variable (especially when you have more than one active uploading session at the same time)
    public static int Progress { get; set; }
```

**Comment by DmitrySikorsky** [comment]
Hi Daniel! Thank you for your question!

I didn't fix that part to keep things simple. To handle multiple sessions you could generate some clientId on client side and put it into cookies. Then, you could have some dictionary (ConcurrentDictionary<TKey, TValue> I think) where key is clientId and value is current progress.

But storing such info inside application/server memory is not the best production-ready approach. It is possible to use some session server etc.
