### ISSUE TITLE
Some improvements

### ISSUE THREAD

**Issue by russellshome** [DmitrySikorsky/AspNetCoreUploadingProgress#6]
Dimitry - very nice code and a good explanation :)

I found a few issues. 

- long totalReadBytes = 0;  Should be outside the main loop of files otherwise it resets to zero after each file.
- The bar is often is left somewhere short of 100%
- Starting an upload while an upload is going has some weird effects.

I saw that someone brought up a multiple sessions issue
https://github.com/DmitrySikorsky/AspNetCoreUploadingProgress/issues/2
The issue as I see it is using multiple windows - not necessarily just sessions.

I've created a fork with a few enhancements & fixes and thought you might be interested.
https://github.com/russellshome/AspNetCoreUploadingProgress

- Uses a "ProgressTracker" to track each upload to enable multiple uploads in different windows or sessions.
- If the user abandons part way through an upload then the upload is abandoned and all files removed.
- Uses a FileSizeLimit to limit the amount of content that can be submitted. This is also checked in javascript prior to submission.

**Comment by DmitrySikorsky** [comment]
Thank you for the comment. This sample just illustrates the idea, so it is far from being perfect. I hope your improvements will help somebody to use it in the real life.
